<?php

/*
 *************************************************************************
 * NFQ eXtremes CONFIDENTIAL
 * [2013] - [2014] NFQ eXtremes UAB
 * All Rights Reserved.
 *************************************************************************
 * NOTICE:
 * All information contained herein is, and remains the property of NFQ eXtremes UAB.
 * Dissemination of this information or reproduction of this material is strictly forbidden
 * unless prior written permission is obtained from NFQ eXtremes UAB.
 *************************************************************************
 */

namespace ONGR\AdminBundle\Security\Authentication\Token;

use Symfony\Component\Security\Core\Authentication\Token\AbstractToken;

/**
 * Token representing session-less user credentials.
 */
class SessionlessToken extends AbstractToken
{
    /**
     * Timestamp indicating cookie's expiration time.
     *
     * @var int
     */
    private $expirationTime;

    /**
     * Cookie's data signature generated by server.
     *
     * @var string
     */
    private $signature;

    /**
     * @var string
     */
    private $ipAddress;

    /**
     * @param string $user
     * @param int $expirationTime
     * @param string $ipAddress
     * @param string $signature
     */
    public function __construct($user, $expirationTime, $ipAddress, $signature)
    {
        parent::__construct([]);

        $this->setUser($user);
        $this->expirationTime = $expirationTime;
        $this->ipAddress = $ipAddress;
        $this->signature = $signature;

        parent::setAuthenticated(false);
    }

    /**
     * {@inheritdoc}
     */
    public function getCredentials()
    {
        return '';
    }

    /**
     * @return int
     */
    public function getExpirationTime()
    {
        return $this->expirationTime;
    }

    /**
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ipAddress;
    }

    /**
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }
}
