<?php

/*
 * This file is part of the ONGR package.
 *
 * (c) NFQ Technologies UAB <info@nfq.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace ONGR\SettingsBundle\Security\Authentication\Token;

use Symfony\Component\Security\Core\Authentication\Token\AbstractToken;

/**
 * Token representing session-less user credentials.
 */
class SessionlessToken extends AbstractToken
{
    /**
     * Timestamp.
     *
     * Timestamp indicating cookie's expiration time.
     *
     * @var int
     */
    private $expirationTime;

    /**
     * Cookie's data signature.
     *
     * Cookie's data signature generated by server.
     *
     * @var string
     */
    private $signature;

    /**
     * @var string
     */
    private $ipAddress;

    /**
     * @param string $user
     * @param int    $expirationTime
     * @param string $ipAddress
     * @param string $signature
     */
    public function __construct($user, $expirationTime, $ipAddress, $signature)
    {
        parent::__construct([]);

        $this->setUser($user);
        $this->expirationTime = $expirationTime;
        $this->ipAddress = $ipAddress;
        $this->signature = $signature;

        parent::setAuthenticated(false);
    }

    /**
     * {@inheritdoc}
     */
    public function getCredentials()
    {
        return '';
    }

    /**
     * @return int
     */
    public function getExpirationTime()
    {
        return $this->expirationTime;
    }

    /**
     * @return string
     */
    public function getIpAddress()
    {
        return $this->ipAddress;
    }

    /**
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }
}
